spring.application.name=hoteles

server.port=8082

# CONEXIÓN A MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/hotel
spring.datasource.username=user
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Elimina la estructura existente y crea las tablas desde cero al iniciar
spring.jpa.hibernate.ddl-auto=create-drop

# Cargar la base siempre
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
